In [20]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.linear_model import SGDClassifier

from matplotlib import pyplot as plt
import seaborn as sns

df = pd.read_csv("Admission_Predict.csv") # Veri setini yüklüyoruz

display(df.head())
display(df.info())
display(df.describe())
print(df.isnull().sum())
print(df.duplicated().sum())

# Veri seti hakkında genel bilgi ediniyoruz

df["Chance of Admit Binary"] = (df["Chance of Admit "] >= 0.75).astype(int) # 0.75 üzerinde olanlar 1, altinda olanlar 0
df["Chance of Admit Binary2"] = (df["Chance of Admit "] >= 0.70).astype(int) # 0.70 için
df["Chance of Admit Binary3"] = (df["Chance of Admit "] >= 0.80).astype(int) # 0.80 için


Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0           1        337          118                  4  4.5   4.5  9.65   
1           2        324          107                  4  4.0   4.5  8.87   
2           3        316          104                  3  3.0   3.5  8.00   
3           4        322          110                  3  3.5   2.5  8.67   
4           5        314          103                  2  2.0   3.0  8.21   

   Research  Chance of Admit   
0         1              0.92  
1         1              0.76  
2         1              0.72  
3         1              0.80  
4         0              0.65

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Serial No.         400 non-null    int64  
 1   GRE Score          400 non-null    int64  
 2   TOEFL Score        400 non-null    int64  
 3   University Rating  400 non-null    int64  
 4   SOP                400 non-null    float64
 5   LOR                400 non-null    float64
 6   CGPA               400 non-null    float64
 7   Research           400 non-null    int64  
 8   Chance of Admit    400 non-null    float64
dtypes: float64(4), int64(5)
memory usage: 28.3 KB


None

Serial No.   GRE Score  TOEFL Score  University Rating         SOP  \
count  400.000000  400.000000   400.000000         400.000000  400.000000   
mean   200.500000  316.807500   107.410000           3.087500    3.400000   
std    115.614301   11.473646     6.069514           1.143728    1.006869   
min      1.000000  290.000000    92.000000           1.000000    1.000000   
25%    100.750000  308.000000   103.000000           2.000000    2.500000   
50%    200.500000  317.000000   107.000000           3.000000    3.500000   
75%    300.250000  325.000000   112.000000           4.000000    4.000000   
max    400.000000  340.000000   120.000000           5.000000    5.000000   

             LOR         CGPA    Research  Chance of Admit   
count  400.000000  400.000000  400.000000        400.000000  
mean     3.452500    8.598925    0.547500          0.724350  
std      0.898478    0.596317    0.498362          0.142609  
min      1.000000    6.800000    0.000000          0.340000  
25%      3.000000    8.170000    0.000000          0.640000  
50%      3.500000    8.610000    1.000000          0.730000  
75%      4.000000    9.062500    1.000000          0.830000  
max      5.000000    9.920000    1.000000          0.970000

Serial No.           0
GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance of Admit      0
dtype: int64
0


In [ ]:
y = df["Chance of Admit Binary"]
X = df.drop(columns=["Serial No.", "Chance of Admit ","Chance of Admit Binary", "Chance of Admit Binary2", "Chance of Admit Binary3"])
# Bağımlı ve bağımsız değişkenleri ayırıyoruz.

scaler = StandardScaler() # StandardScaler kullanıyoruz.
scaled_data = scaler.fit_transform(X)
# Verileri standartlaştırıyoruz.

X_train, X_test, y_train, y_test = train_test_split(scaled_data, y, test_size=0.20, random_state=42) # Veri setini eğitim ve test setlerine ayırıyoruz.


In [ ]:
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)
# Modeli eğitim verisi ile eğitiyoruz.

y_pred = model.predict(X_test) # Test verisi ile tahmin yapıyoruz.

conf_matrix = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:")
print(conf_matrix)
# Confusion matrix'i yazdırıyoruz.

accuracy = accuracy_score(y_test, y_pred)
print(f"Model Doğruluk Oranı: {accuracy:.2f}")
print("\nSınıflandırma Raporu:")
print(classification_report(y_test, y_pred))
# Sınıflandırma raporunu yazdırıyoruz.


Confusion Matrix:
[[42  5]
 [ 2 31]]
Model Doğruluk Oranı: 0.91

Sınıflandırma Raporu:
              precision    recall  f1-score   support

           0       0.95      0.89      0.92        47
           1       0.86      0.94      0.90        33

    accuracy                           0.91        80
   macro avg       0.91      0.92      0.91        80
weighted avg       0.92      0.91      0.91        80



In [ ]:
sgd_model = SGDClassifier(loss="log_loss", max_iter=1000, tol=1e-4, random_state=42, verbose=1) # SGDClassifier modelini oluşturuyoruz.

# Modeli SGDClassifier ile oluşturuyoruz.
sgd_model.fit(X_train, y_train.values.ravel())

-- Epoch 1
Norm: 37.39, NNZs: 7, Bias: -3.463899, T: 320, Avg. loss: 3.858803
Total training time: 0.00 seconds.
-- Epoch 2
Norm: 24.92, NNZs: 7, Bias: 5.580665, T: 640, Avg. loss: 2.754257
Total training time: 0.00 seconds.
-- Epoch 3
Norm: 23.83, NNZs: 7, Bias: -6.752102, T: 960, Avg. loss: 2.259411
Total training time: 0.00 seconds.
-- Epoch 4
Norm: 19.03, NNZs: 7, Bias: -1.539796, T: 1280, Avg. loss: 1.698976
Total training time: 0.00 seconds.
-- Epoch 5
Norm: 14.42, NNZs: 7, Bias: 1.233616, T: 1600, Avg. loss: 1.657292
Total training time: 0.00 seconds.
-- Epoch 6
Norm: 15.12, NNZs: 7, Bias: -2.388301, T: 1920, Avg. loss: 1.472138
Total training time: 0.00 seconds.
-- Epoch 7
Norm: 11.64, NNZs: 7, Bias: -0.051688, T: 2240, Avg. loss: 1.477854
Total training time: 0.00 seconds.
-- Epoch 8
Norm: 9.28, NNZs: 7, Bias: -8.337733, T: 2560, Avg. loss: 1.033451
Total training time: 0.00 seconds.
-- Epoch 9
Norm: 9.15, NNZs: 7, Bias: -0.548798, T: 2880, Avg. loss: 1.106754
Total training t

SGDClassifier(loss='log_loss', random_state=42, tol=0.0001, verbose=1)

In [ ]:
# Veri setinin üzerinden 54 kere geçtikten sonra modelin ağırlıklarını ve bias'ını yazdırıyoruz.
print(f"Son Ağırlıklar (w): {sgd_model.coef_}")
print(f"\nSon Bias (b): {sgd_model.intercept_} \n")


importance_df = pd.DataFrame({"Özellik": X.columns,"Katsayı": model.coef_[0]}) # Önem sırasını yazdırabilmek için Özellik isimleri ve önem katsayılarını içeren bir DataFrame oluşturuyoruz.

# Katsayının mutlak değeriyle önem sıralaması yapıyoruz.
importance_df["Mutlak Katsayı"] = importance_df["Katsayı"].abs()
importance_df = importance_df.sort_values(by="Mutlak Katsayı", ascending=False)

print("Önem sırasına göre değişkenlerin katsayıları:")
print(importance_df[["Özellik", "Katsayı"]])
# Özelliklerin önem sırasını yazdırıyoruz.

Son Ağırlıklar (w): [[ 1.05759264  0.20564499  0.66702309  0.77903064 -0.3100472   2.25379537
   0.58811616]]

Son Bias (b): [-1.06432791] 

Önem sırasına göre değişkenlerin katsayıları:
             Özellik   Katsayı
5               CGPA  1.777295
0          GRE Score  0.729352
3                SOP  0.420920
6           Research  0.411233
1        TOEFL Score  0.350700
2  University Rating  0.309486
4               LOR   0.253028


In [25]:
y = df["Chance of Admit Binary2"] # 0.70 eşik değeri ile ikili sınıflandırma
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42) # Veri setini eğitim ve test setlerine ayırıyoruz.

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)
# Modeli 0.70 eşik değeri ile eğitim verisi ile eğitiyoruz.

y_pred = model.predict(X_test)

conf_matrix = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:")
print(conf_matrix)
# Confusion matrix'i yazdırıyoruz.

accuracy = accuracy_score(y_test, y_pred)
print(f"Model Doğruluk Oranı: {accuracy:.2f}")
print("\nSınıflandırma Raporu:")
print(classification_report(y_test, y_pred))
# Modelin doğruluk oranını ve sınıflandırma raporunu yazdırıyoruz.

# Aynı adımları 0.70 eşik değeri için yapıyoruz.


Confusion Matrix:
[[29  3]
 [ 5 43]]
Model Doğruluk Oranı: 0.90

Sınıflandırma Raporu:
              precision    recall  f1-score   support

           0       0.85      0.91      0.88        32
           1       0.93      0.90      0.91        48

    accuracy                           0.90        80
   macro avg       0.89      0.90      0.90        80
weighted avg       0.90      0.90      0.90        80



In [ ]:
y = df["Chance of Admit Binary3"] # 0.80 ve üzeri kabul oranı için ikili sınıflandırma
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42) # Veri setini eğitim ve test setlerine ayırıyoruz.

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)
# Modeli 0.80 eşik değeri ile eğitim verisi ile eğitiyoruz.

y_pred = model.predict(X_test)

conf_matrix = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:")
print(conf_matrix) # Confusion matrix'i yazdırıyoruz.

accuracy = accuracy_score(y_test, y_pred)
print(f"Model Doğruluk Oranı: {accuracy:.2f}")
print("\nSınıflandırma Raporu:")
print(classification_report(y_test, y_pred))
# Modelin doğruluk oranını ve sınıflandırma raporunu yazdırıyoruz.

# Aynı adımları 0.80 eşik değeri için yapıyoruz.


Confusion Matrix:
[[49  2]
 [ 3 26]]
Model Doğruluk Oranı: 0.94

Sınıflandırma Raporu:
              precision    recall  f1-score   support

           0       0.94      0.96      0.95        51
           1       0.93      0.90      0.91        29

    accuracy                           0.94        80
   macro avg       0.94      0.93      0.93        80
weighted avg       0.94      0.94      0.94        80



Modellerimize baktığımızda genel olarak iyi sonuçlar aldığımızı görebiliriz. En iyi sonuç 0.80 eşik değeri ile %94 accuracy puanı ile elde edilmiştir. Bu sebeple Logistic regression için tercih edilen eşik değeri 0.80'dir.

Modelin geliştirilmesi için farklı yöntemler deneyebiliriz. Örneğin, modelin hiperparametrelerini en iyi halinde ayarlamak için GridSearchCV veya RandomizedSearchCV gibi yöntemler kullanabiliriz. 

Ayrıca, modelin performansını artırmak için daha karmaşık modeller deneyebiliriz. 
Örneğin, karar ağaçları (Decision Tree), rastgele ormanlar (Random Forest) veya destek vektör makineleri (Support Vector Machine (SVM)) gibi daha karmaşık algoritmalar kullanılabilir.
Bu tarz modelleri kullandıktan sonra Ensemble öğrenme metodu ile hepsinin karışımını kullanarak daha sağlıklı tahminler yapılabilir.

Bunun yanı sıra, modelin performansını artırmak için daha fazla veri toplamak veya veri ön işleme adımlarını iyileştirmek de faydalı olabilir. 
Özellikle özellik mühendisliği yapmak gibi adımlar modelin başarısını artırabilir. 

Tek bir eğitim‑test bölmesi yerine, k‑fold cross‑validation uygulayarak modelin farklı veri dilimlerinde ne kadar istikrarlı performans gösterdiğini ölçebilir, aşırı öğrenmeyi (overfitting) tespit edebiliriz.